# Generated by Django 5.0 on 2024-01-04 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('designation', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('projects', models.CharField(blank=True, max_length=200, null=True)),
                ('teamunit', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('citycountry', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('reportingmanager', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('doj', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bridge_app.user')),
                ('bday', models.DateField(blank=True, null=True)),
                ('tshirtsize', models.DecimalField(blank=True, decimal_places=2, help_text='Enter size in cms', max_digits=5, null=True)),
                ('mailaddress', models.CharField(blank=True, max_length=255, null=True)),
                ('recentpraises', models.TextField(blank=True, null=True)),
                ('culturalaffiliation', models.CharField(blank=True, choices=[('culture1', 'Culture 1'), ('culture2', 'Culture 2')], max_length=255, null=True)),
                ('hobbies', models.CharField(blank=True, choices=[('hobby1', 'Hobby 1'), ('hobby2', 'Hobby 2')], max_length=255, null=True)),
                ('learninggoals', models.TextField(blank=True, null=True)),
                ('skills_inspiration', models.TextField(blank=True, db_column='skills&inspiration', null=True)),
                ('abouther', models.TextField(blank=True, null=True)),
                ('wordsfromher', models.TextField(blank=True, max_length=500, null=True)),
                ('educational_proofs', models.BinaryField(blank=True, null=True)),
                ('nda_proofs', models.BinaryField(blank=True, null=True)),
                ('government_proofs', models.BinaryField(blank=True, null=True)),
                ('policy_acknowledgment', models.BinaryField(blank=True, null=True)),
                ('offer_promotions', models.BinaryField(blank=True, null=True)),
                ('probation_duration', models.DateField(blank=True, null=True)),
                ('entry_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('first_hike', models.CharField(blank=True, max_length=100, null=True)),
                ('hike_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hike_date', models.DateField(blank=True, null=True)),
                ('custom_hobby', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
