# Generated by Django 5.0.1 on 2024-01-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0002_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='projects',
            field=models.IntegerField(null=True),
        ),
    ]
