# Generated by Django 5.0.1 on 2024-01-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0003_userpreferences_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='projects',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
