# Generated by Django 5.0.1 on 2024-01-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0004_alter_userpreferences_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='display_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='display_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='display_team',
            field=models.BooleanField(default=True),
        ),
    ]
