# Generated by Django 5.0.1 on 2024-01-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0007_alter_userpreferences_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='display_team',
            field=models.BooleanField(default=True),
        ),
    ]
