# Generated by Django 5.0.1 on 2024-01-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0008_userpreferences_display_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='display_citycountry',
            field=models.BooleanField(default=True),
        ),
    ]
