# Generated by Django 5.0.1 on 2024-01-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0009_userpreferences_display_citycountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='display_reporting_manager',
            field=models.BooleanField(default=True),
        ),
    ]
