# Generated by Django 5.0.1 on 2024-01-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0010_userpreferences_display_reporting_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='doj',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
