# Generated by Django 5.0.1 on 2024-01-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0012_employee_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
