# Generated by Django 5.0.1 on 2024-01-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0013_user_country_user_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file_name',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
