# Generated by Django 5.0.1 on 2024-01-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0014_alter_user_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
