# Generated by Django 5.0.1 on 2024-01-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0015_alter_user_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='doj',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
