<?php 
ob_start();
include('../../includes/config.php');
include(ROOT_PATH.'includes/connect.php');
session_start();
echo $id_get=$_REQUEST['id'];
$role=$_REQUEST['role'];
$Dashboard=$_REQUEST['Dashboard']?$_REQUEST['Dashboard']:'0';
$phase_page=$_REQUEST['phase_page']?$_REQUEST['phase_page']:'0';
$class_page=$_REQUEST['class_page']?$_REQUEST['class_page']:'0';
$actual=$_REQUEST['actual']?$_REQUEST['actual']:'0';
$sim=$_REQUEST['sim']?$_REQUEST['sim']:'0';
$Academic=$_REQUEST['Academic']?$_REQUEST['Academic']:'0';
$Testing=$_REQUEST['Testing']?$_REQUEST['Testing']:'0';
$evaluation=$_REQUEST['evaluation']?$_REQUEST['evaluation']:'0';
$Task=$_REQUEST['Task']?$_REQUEST['Task']:'0';
$Student=$_REQUEST['Student']?$_REQUEST['Student']:'0';
$Emergency=$_REQUEST['Emergency']?$_REQUEST['Emergency']:'0';
$Qual=$_REQUEST['Qual']?$_REQUEST['Qual']:'0';
$Clearance=$_REQUEST['Clearance']?$_REQUEST['Clearance']:'0';
$CAP=$_REQUEST['CAP']?$_REQUEST['CAP']:'0';
$Memo=$_REQUEST['Memo']?$_REQUEST['Memo']:'0';
$Report=$_REQUEST['Report']?$_REQUEST['Report']:'0';
$Discipline=$_REQUEST['Discipline']?$_REQUEST['Discipline']:'0';
$Start0=$_REQUEST['Start0']?$_REQUEST['Start0']:'0';
$Datapage=$_REQUEST['Datapage']?$_REQUEST['Datapage']:'0';
$CTP=$_REQUEST['CTP']?$_REQUEST['CTP']:'0';
$Newcourse=$_REQUEST['Newcourse']?$_REQUEST['Newcourse']:'0';
$sidebar_phase=$_REQUEST['sidebar_phase']?$_REQUEST['sidebar_phase']:'0';
$Quiz=$_REQUEST['Quiz']?$_REQUEST['Quiz']:'0';
$select_Course=$_REQUEST['select_Course']?$_REQUEST['select_Course']:'0';
$select_student_details=$_REQUEST['select_student_details']?$_REQUEST['select_student_details']:'0';
$course_details=$_REQUEST['course_details']?$_REQUEST['course_details']:'0';
$landing_page=$_REQUEST['landing_page']?$_REQUEST['landing_page']:'0';
$checklist_pages=$_REQUEST['checklist_pages']?$_REQUEST['checklist_pages']:'0';
$clone_delete=$_REQUEST['clone_delete']?$_REQUEST['clone_delete']:'0';
$fill_gradsheet=$_REQUEST['fill_gradsheet']?$_REQUEST['fill_gradsheet']:'0';
$reset_gradsheet=$_REQUEST['reset_gradsheet']?$_REQUEST['reset_gradsheet']:'0';
$Unlock_gradsheet=$_REQUEST['Unlock_gradsheet']?$_REQUEST['Unlock_gradsheet']:'0';
$askUnlock_gradsheet=$_REQUEST['askUnlock_gradsheet']?$_REQUEST['askUnlock_gradsheet']:'0';
$askreset_gradsheet=$_REQUEST['askreset_gradsheet']?$_REQUEST['askreset_gradsheet']:'0';
$give_per_gradsheet=$_REQUEST['give_per_gradsheet']?$_REQUEST['give_per_gradsheet']:'0';
$ask_per_gradsheet=$_REQUEST['ask_per_gradsheet']?$_REQUEST['ask_per_gradsheet']:'0';
$give_Acedemic=$_REQUEST['give_Acedemic']?$_REQUEST['give_Acedemic']:'0';
$Clear_Acedemic=$_REQUEST['Clear_Acedemic']?$_REQUEST['Clear_Acedemic']:'0';
$ask_Acedemic=$_REQUEST['ask_Acedemic']?$_REQUEST['ask_Acedemic']:'0';
$delete_task=$_REQUEST['delete_task']?$_REQUEST['delete_task']:'0';
$give_marks_evalution=$_REQUEST['give_marks_evalution']?$_REQUEST['give_marks_evalution']:'0';
$view_marks_evalution=$_REQUEST['view_marks_evalution']?$_REQUEST['view_marks_evalution']:'0';
$give_marks_test=$_REQUEST['give_marks_test']?$_REQUEST['give_marks_test']:'0';
$unlock_test=$_REQUEST['unlock_test']?$_REQUEST['unlock_test']:'0';
$askunlock_test=$_REQUEST['askunlock_test']?$_REQUEST['askunlock_test']:'0';
$unlock_test=$_REQUEST['unlock_test']?$_REQUEST['unlock_test']:'0';
$export_course=$_REQUEST['export_course']?$_REQUEST['export_course']:'0';
$add_attachment_test=$_REQUEST['add_attachment_test']?$_REQUEST['add_attachment_test']:'0';
$delete_emergance=$_REQUEST['delete_emergance']?$_REQUEST['delete_emergance']:'0';
$assign_Cap=$_REQUEST['assign_Cap']?$_REQUEST['assign_Cap']:'0';
$Create_memo=$_REQUEST['Create_memo']?$_REQUEST['Create_memo']:'0';
$Edit_memo=$_REQUEST['Edit_memo']?$_REQUEST['Edit_memo']:'0';
$Delete_memo=$_REQUEST['Delete_memo']?$_REQUEST['Delete_memo']:'0';
$Delete_course=$_REQUEST['Delete_course']?$_REQUEST['Delete_course']:'0';
$Edit_landing=$_REQUEST['Edit_landing']?$_REQUEST['Delete_course']:'0';
$Delete_landing=$_REQUEST['Delete_landing']?$_REQUEST['Delete_landing']:'0';
$Delete_landing=$_REQUEST['Delete_landing']?$_REQUEST['Delete_landing']:'0';
$askclone_delete=$_REQUEST['askclone_delete']?$_REQUEST['askclone_delete']:'0';
$course_phase_man_dashbirad=$_REQUEST['course_phase_man_dashbirad']?$_REQUEST['course_phase_man_dashbirad']:'0';
$test_dasborad=$_REQUEST['test_dasborad']?$_REQUEST['test_dasborad']:'0';
$coursemanager=$_REQUEST['coursemanager']?$_REQUEST['coursemanager']:'0';
 $phasemanager=$_REQUEST['phasemanager']?$_REQUEST['phasemanager']:'0';
 $assingeresource=$_REQUEST['assingeresource']?$_REQUEST['assingeresource']:'0';
$array=serialize(array(
"Dashboard"=>$Dashboard,
"phase_page"=>$phase_page,
"class_page"=>$class_page,
"actual"=>$actual,
"sim"=>$sim,
"Academic"=>$Academic,
"Testing"=>$Testing,
"evaluation"=>$evaluation,
"Task"=>$Task,
"Student"=>$Student,
"Emergency"=>$Emergency,
"Qual"=>$Qual,
"Clearance"=>$Clearance,
"CAP"=>$CAP,
"Memo"=>$Memo,
"Report"=>$Report,
"Discipline"=>$Discipline,
"Start0"=>$Start0,
"Datapage"=>$Datapage,
"CTP"=>$CTP,
"Newcourse"=>$Newcourse,
"sidebar_phase"=>$sidebar_phase,
"Quiz"=>$Quiz,
"select_Course"=>$select_Course,
"select_student_details"=>$select_student_details,
"course_details"=>$course_details,
"landing_page"=>$landing_page,
"checklist_pages"=>$checklist_pages,
"clone_delete"=>$clone_delete,
"askclone_delete"=>$askclone_delete,
"fill_gradsheet"=>$fill_gradsheet,
"reset_gradsheet"=>$reset_gradsheet,
"Unlock_gradsheet"=>$Unlock_gradsheet,
"askUnlock_gradsheet"=>$askUnlock_gradsheet,
"askreset_gradsheet"=>$askreset_gradsheet,
"give_per_gradsheet"=>$give_per_gradsheet,
"ask_per_gradsheet"=>$ask_per_gradsheet,
"give_Acedemic"=>$give_Acedemic,
"Clear_Acedemic"=>$Clear_Acedemic,
"ask_Acedemic"=>$ask_Acedemic,
"delete_task"=>$delete_task,
"give_marks_evalution"=>$give_marks_evalution,
"view_marks_evalution"=>$view_marks_evalution,
"give_marks_test"=>$give_marks_test,
"unlock_test"=>$unlock_test,
"askunlock_test"=>$askunlock_test,
"unlock_test"=>$unlock_test,
"add_attachment_test"=>$add_attachment_test,
"delete_emergance"=>$delete_emergance,
"assign_Cap"=>$assign_Cap,
"Create_memo"=>$Create_memo,
"Edit_memo"=>$Edit_memo,
"Delete_memo"=>$Delete_memo,
"Delete_course"=>$Delete_course,
"Edit_landing"=>$Edit_landing,
"Delete_landing"=>$Delete_landing,
"alerts"=>$alerts,
"export_course"=>$export_course,
"course_phase_man_dashbirad"=>$course_phase_man_dashbirad,
"test_dasborad"=>$test_dasborad,
"coursemanager"=>$coursemanager,
"phasemanager"=>$phasemanager,
"assingeresource"=>$assingeresource,
));

$sql ="UPDATE `roles` SET `permission` = '$array' WHERE `id`='$id_get'";;

$statement = $connect->prepare($sql);

$statement->execute();  
  $_SESSION['success'] = "Data Edited Successfully";
  ob_end_clean();
header('Location:role-update.php?id='.$id_get.'&name='.$role);
exit;
?>
