
<?php
include('../config.php');
include(ROOT_PATH . 'includes/connect.php');
session_start();
?>

<?php
if (isset($_REQUEST['truncateData'])) {
    $adminPassword = $_REQUEST['adminPassword'];
    $password = md5($adminPassword);

    $adminQuery = $connect->query("SELECT COUNT(*) FROM users WHERE role = 'super admin' AND password = '$password'");
    $data = $adminQuery->fetchColumn();
    if ($data != 0) {
        $sql = "TRUNCATE TABLE academic";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE accomplish_task";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE acedemic_phase";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE acedemic_stu";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE actual";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE actual_gradesheet";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE actual_phase";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE additional_task";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE adminpagechangelog";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE briefcase";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE clearance_data";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE clearance_student_id";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE cloned_gradesheet";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE clone_class";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE ctppage";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE discipline";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE discipline_data";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE editor_data";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE emergency_data";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE favouritefiles";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE favouritepages";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE filepermissions";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE filepermissionsfm";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE files";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE file_briefcase";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE file_briefcase_folder";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE folders";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE folder_shop_user";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE gradesheet";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE grade_per_notifications";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE groups";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE group_student_scheduling";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE homepage";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE item";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE itembank";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE item_clone_gradesheet";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE item_gradesheet";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE library";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE mark_distribution";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE meesages";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE memo";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE newcourse";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE newpagechangelogdata";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE newpage_fm";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE notifications";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE pagepermissions";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE pagepermissionsfm";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE phase";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE popup";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE prereuisites";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE prereuisite_data";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE qual_data";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE quiz";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE quiz_cloned_data";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE quiz_marks";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE self";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE shelf";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE shelf_shop";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE shops";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE shop_folder";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE sidebar_ctp";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE sim";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE sim_phase";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE subitem";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE subitem_cloned_gradesheet";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE subitem_gradesheet";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE sub_item";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE test";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE test_cloned_data";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE test_data";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE test_phase";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE type_category_data";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE type_data";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE user_briefcase";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE user_files";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE vehicle";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE vehicletype";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE warning_category_data";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE warning_data";
        $connect->query($sql);
        $sql = "TRUNCATE TABLE warning_permission";
        $connect->query($sql);
        $sql = "DELETE FROM users WHERE role != 'super admin';";
        $connect->query($sql);
        $_SESSION['success'] = "Data Truncated Successfully";
        header('Location:dataBase.php');
    } else {
        
        $_SESSION['warning'] = "Please Enter Valid Password";
        header('Location:dataBase.php');
    }
}
?>
